parser: babel-eslint

extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
  - plugin:react/recommended
  - plugin:jest/recommended
  # - plugin:security/recommended

plugins:
  - prettier
  - import
  - react
  - jest
  - babel
  # - jsx-ally
  # - security

env:
  browser: true
  node: true
  es6: true
  jest: true
  jest/globals: true

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true

# globals:
#   {
#     describe: true,
#     it: true,
#     expect: true,
#     beforeEach: true,
#     afterEach: true,
#     beforeAll: true,
#     afterAll: true,
#   }

rules:
  # this should be removed at some point
  # current workaround is to have second package.json
  # https://github.com/eslint/eslint/issues/12319
  # silences  errors related stemming from second package.json
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  react/no-array-index-key: 0
  no-unused-vars: 1
  prefer-destructuring: 1
  prettier/prettier: warn
  no-underscore-dangle: 0
  comma-dangle: 0
  global-require: 0
  # [
  #   'warn',
  #   {
  #     arrays: 'always-multiline',
  #     objects: 'always-multiline',
  #     imports: 'never',
  #     exports: 'never',
  #     functions: 'never',
  #   },
  # ]
  semi: 1
  no-console: 0
# settings:
# import/resolver:
#   node:
#     paths: [src]
# react:
#   pragma: React
#   version: 16.8.0
