parser: babel-eslint

extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
  - plugin:react/recommended
  - plugin:jest/recommended

plugins:
  - prettier
  - import
  - react
  - jest
  - babel

# settings:

env:
  browser: true
  node: true
  es6: true
  jest: true
  jest/globals: true

# globals:

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true

rules:
  prettier/prettier: warn
  comma-dangle:
    [
      'warn',
      {
        arrays: 'always',
        objects: 'always',
        imports: 'never',
        exports: 'never',
        functions: 'never',
      },
    ]
  semi: 1
  no-console: 0
# settings:
# import/resolver:
#   node:
#     paths: [src]
# react:
#   pragma: React
#   version: 16.8.0
