parser: babel-eslint

extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
  - plugin:react/recommended
  - plugin:jest/recommended

plugins:
  - prettier
  - import
  - react
  - jest
  - babel

env:
  browser: true
  node: true
  es6: true
  jest: true
  jest/globals: true

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true

rules:
  # this should be removed at some point
  # current workaround is to have second package.json
  # https://github.com/eslint/eslint/issues/12319
  # silences  errors related stemming from second package.json
  import/no-extraneous-dependencies: 0
  prettier/prettier: warn
  comma-dangle:
    [
      'warn',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'never',
        exports: 'never',
        functions: 'never',
      },
    ]
  semi: 1
  no-console: 0
# globals:
# settings:
# import/resolver:
#   node:
#     paths: [src]
# react:
#   pragma: React
#   version: 16.8.0
